runtime: nodejs18

instance_class: F2

env_variables:
  HOTEL_ID: "hotel1"
  # Diğer çevresel değişkenler burada tanımlanabilir
  # MONGODB_URI: "mongodb+srv://..."
  # SMTP_USER: "..."
  # Güvenlik nedeniyle hassas bilgileri buraya yazmak yerine
  # Google Cloud Secret Manager kullanmanızı öneririz

automatic_scaling:
  min_instances: 1
  max_instances: 5
  min_idle_instances: 1

handlers:
- url: /.*
  script: auto
  secure: always 